### ISSUE TITLE
python script error after running update.py

### ISSUE THREAD

**Issue by Vikhamar** [dev-cafe/autocmake#271]
If I run update.py --self and then run ./setup <build_directory> I get python error message:
Traceback (most recent call last):
  File "/home/rasmus/ReSpect/source/./setup", line 120, in <module>
    configure.configure(root_directory, build_path, cmake_command, arguments['--show'])
  File "/home/rasmus/ReSpect/source/cmake/autocmake/configure.py", line 152, in configure
    if not arguments['--show']:
TypeError: 'bool' object is not subscriptable

**Comment by bast** [comment]
Thanks for reporting! I will try to reproduce this and report back.
